include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Watchvib

Watchvib_FILES = Watchvib.xm
Watchvib_FRAMEWORKS = CoreTelephony AudioToolbox


Watchvib_CFLAGS = -fobjc-arc

export ARCHS = armv7 arm64
Watchvib_ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/tweak.mk
	
	
all::
	