include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WatchvibSB

WatchvibSB_FILES = WatchvibSB.xm


WatchvibSB_CFLAGS = -fobjc-arc
export ARCHS = armv7 arm64
WatchvibSB_ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/tweak.mk

all::

	
